### ISSUE TITLE
ToDo Liste - Anwendung - v1.0

### ISSUE THREAD

**Issue by archer96** [archer96/SPAZ#3]
# ToDo Liste für den Code-Bereich der Anwendung für v1.0#

## Nutzerrollen / Rechte
- [ ] Admin kann Nutzerrollen bearbeiten
- [ ] Admin kann Nutzerrollen hinzufügen

## Design
- [ ] Familien-Design fertigstellen
- [ ] Nachweis-Design fertigstellen
- [ ] Jugendämter-Design fertigstellen
- [ ] Error-Design fertigstellen
- [ ] Firmenlogo einbinden
- [ ] Design abschließen

## UX
- [ ] AJAX laden von Inhalten (Seite muss nicht immer gewechselt werden)
- [ ] Nutzer in Bedienung einführen (Tipps)
- [ ] Hilfe Seiten

- [ ] ...
