### ISSUE TITLE
ToDo Liste - Anwendung - v0.2

### ISSUE THREAD

**Issue by archer96** [archer96/SPAZ#4]
# ToDo Liste für den Code-Bereich der Anwendung für v0.2#

## Nachweise
- [x] Nachweise filtern
- [x] Funktion korrekt (wie in der Access Datenbank)

## Admin
- [x] Logs löschen (clear)

## UX
- [x] Erfolgsmeldung nach Erstellen von Objekten
- [x] -> Bei Familien
- [x] -> Bei Maßnahmen
- [x] -> Bei Fachleistungsstunden
- [x] -> Bei Nachweisen
- [x] -> Bei Nachweiszeilen
- [x] Hilfe Seiten

## Diagramme
- [x] Ablaufdiagramme
